# Generated by Django 2.2.5 on 2021-06-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalSales', models.FloatField()),
                ('dateOfSales', models.DateTimeField(verbose_name='date recorded')),
                ('branchOfOrigin', models.TextField()),
            ],
        ),
    ]
