# Generated by Django 2.2.5 on 2021-06-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='SalesRecord',
        ),
    ]
