# Generated by Django 2.2.5 on 2021-07-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210624_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemSalesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfSales', models.DateTimeField(verbose_name='date recorded')),
                ('menuItem', models.TextField()),
                ('menuItemPrice', models.FloatField()),
                ('quantitySold', models.IntegerField()),
            ],
        ),
    ]
