# Generated by Django 2.2.5 on 2021-07-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_menuitemsalesrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRecorded', models.DateTimeField(verbose_name='date recorded')),
                ('expensesType', models.TextField()),
                ('totalExpenses', models.FloatField()),
                ('quantityExpenses', models.IntegerField()),
            ],
        ),
    ]
