# Generated by Django 2.2.5 on 2021-07-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_expensesrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesrecord',
            name='expensesType',
            field=models.CharField(choices=[('Electricity', 'Electricity'), ('Stock Resupply', 'Stock Resupply'), ('Rent', 'Rent'), ('Worker Salary', 'Worker Salary')], max_length=100),
        ),
    ]
