# Generated by Django 2.2.5 on 2021-07-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210708_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='branchOfOrigin',
            field=models.CharField(choices=[('Selangor', 'Selangor'), ('Johor', 'Johor'), ('Perak', 'Perak'), ('Pahang', 'Pahang')], max_length=100),
        ),
    ]
