# Generated by Django 2.2.5 on 2021-07-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210708_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesrecord',
            name='dateRecorded',
            field=models.DateTimeField(verbose_name='date recorded'),
        ),
        migrations.AlterField(
            model_name='menuitemsalesrecord',
            name='dateOfSales',
            field=models.DateTimeField(verbose_name='date recorded'),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='dateOfSales',
            field=models.DateTimeField(verbose_name='date recorded'),
        ),
    ]
