# Generated by Django 2.2.5 on 2021-07-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesrecord',
            name='expensesType',
            field=models.CharField(choices=[('Utilities', 'Utilities'), ('Stock Resupply', 'Stock Resupply'), ('Rent', 'Rent'), ('Worker Salary', 'Worker Salary')], max_length=100),
        ),
    ]
